// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtSFBUwe3b0StaoSGGkXWTm_GxH69E_KM',
    appId: '1:257462774742:web:6a988d9f4fae3773069277',
    messagingSenderId: '257462774742',
    projectId: 'c121890',
    authDomain: 'c121890.firebaseapp.com',
    storageBucket: 'c121890.firebasestorage.app',
    measurementId: 'G-PL9T2V3JJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLilquOToMRkIOgd-A3yaH9suZrO8_tH4',
    appId: '1:257462774742:android:a9862ed3d1e4b6b2069277',
    messagingSenderId: '257462774742',
    projectId: 'c121890',
    storageBucket: 'c121890.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3dj6188H3qN_qNLoBWP7Y4LMnX4gT9uY',
    appId: '1:257462774742:ios:fb0bcf3190f63612069277',
    messagingSenderId: '257462774742',
    projectId: 'c121890',
    storageBucket: 'c121890.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3dj6188H3qN_qNLoBWP7Y4LMnX4gT9uY',
    appId: '1:257462774742:ios:fb0bcf3190f63612069277',
    messagingSenderId: '257462774742',
    projectId: 'c121890',
    storageBucket: 'c121890.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtSFBUwe3b0StaoSGGkXWTm_GxH69E_KM',
    appId: '1:257462774742:web:39bf991c5b3a0e42069277',
    messagingSenderId: '257462774742',
    projectId: 'c121890',
    authDomain: 'c121890.firebaseapp.com',
    storageBucket: 'c121890.firebasestorage.app',
    measurementId: 'G-N8MRKZXTJE',
  );

}